### ISSUE TITLE
_assert _ouput_contains does not work if optional message is specified

### ISSUE THREAD

**Issue by johngassman-ws** [Checksum/critic.sh#4]
_output_contains is grep'ing for all following args ("$*") which breaks if you specify an optional message

Example:
Given a method that just: 
`echo "Gimme some foo"`

Happy path:
`_assert _output_contains "foo"`

Unhappy path:
`_assert _output_contains "foo" "there is foo"`

Changing the _output_contains function to:
`grep -Fqi "$1" <<< "$_output"`
appears to fix the issue.

**Comment by Checksum** [comment]
Thanks for the bug report! Should be a straightforward fix like you pointed out. Will get it in ASAP.
